name: Build and push to Dockerhub
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: liujordan/directory-watch
          tags: latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}