name: Build and push to Dockerhub
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0

      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: liujordan/directory-watch
          tag: latest
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}